<!DOCTYPE html>
<?php include ("./controller/main.php");?>
<html class="no-js" lang="<?=$lang?>">
<head>
    <?php sectionhead($db)?>
</head>

<body>
    <?php sectiontopbar($trans);?>

    <?php sectionheader($db, 0, $trans); ?>

    <?php sectionbreadcrumb('|legal', $trans);?>

    <div class="section section-padding">
        <div class="container">
            <div class="section-title3">
                <p><strong>I. INFORMACI&Oacute;N GENERAL</strong></p>
                <p>La titularidad de este sitio web, farmacialosllanos.org, (en adelante Sitio Web) la ostenta: FARMACIA LOS LLANOS, provista de NIF: 23242441K e inscrita en: Registro Mercantil de la provincia de Almer&iacute;a; y cuyos datos registrales son: Tomo 2095; Folio 10, inscripci&oacute;n 1&ordm;, Hoja Al-58275, y cuyos datos de contacto son:</p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Direcci&oacute;n: C/Potasio 7, Loma Cabrera (Almería)<br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tel&eacute;fono de contacto: (+34) 950 33 70 53<br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Email de contacto: contacto@farmacialosllanos.org</p>
                <p>Este documento (as&iacute; como todo otro documentos que aqu&iacute; se mencionen) regula las condiciones por las que se rige el uso de este Sitio Web (farmacialosllanos.org) y la compra o adquisici&oacute;n de productos y/o servicios en el mismo (en adelante, Condiciones).</p>
                <p>A efectos de estas Condiciones se entiende que la actividad que Farmacia los llanos desarrolla a trav&eacute;s del Sitio Web comprende:</p>
                <p>Comercializaci&oacute;n y distribuci&oacute;n de productos de farmacia y parafarmacia, siempre conforme con la normativa sanitaria vigente.</p>
                <p>Adem&aacute;s de leer las presentes Condiciones, antes de acceder, navegar y/o usar esta p&aacute;gina web, el Usuario ha de haber le&iacute;do el Aviso Legal y las Condiciones Generales de Uso, incluyendo, la pol&iacute;tica de cookies, y la pol&iacute;tica de privacidad y de protecci&oacute;n de datos de Farmacia los llanos. Al utilizar este Sitio Web o al hacer y/o solicitar la adquisici&oacute;n de un producto y/o servicio a trav&eacute;s del mismo el Usuario consiente quedar vinculado por estas Condiciones y por todo lo anteriormente mencionado, por lo que si no est&aacute; de acuerdo con todo ello, no debe usar este Sitio Web.</p>
                <p>Asimismo, se informa que estas Condiciones podr&iacute;an ser modificadas. El Usuario es responsable de consultarlas cada vez que acceda, navegue y/o use el Sitio Web ya que ser&aacute;n aplicables aquellas que se encuentren vigentes en el momento en que se solicite la adquisici&oacute;n de productos y/o servicios.</p>
                <p>Para todas las preguntas que el Usuario pueda tener en relaci&oacute;n con las Condiciones puede ponerse en contacto con el titular utilizando los datos de contacto facilitados m&aacute;s arriba o, en su caso, utilizando el formulario de contacto.</p>
                
                <p><strong>II. EL USUARIO</strong></p>
                <p>El acceso, la navegaci&oacute;n y uso del Sitio Web, confiere la condici&oacute;n de usuario (en adelante referido, indistintamente, individualmente como Usuario o conjuntamente como Usuarios), por lo que se aceptan, desde que se inicia la navegaci&oacute;n por el Sitio Web, todas las Condiciones aqu&iacute; establecidas, as&iacute; como sus ulteriores modificaciones, sin perjuicio de la aplicaci&oacute;n de la correspondiente normativa legal de obligado cumplimiento seg&uacute;n el caso.</p>
                <p>El Usuario asume su responsabilidad de un uso correcto del Sitio Web. Esta responsabilidad se extender&aacute; a:</p>
                <ul>
                    <li>Hacer uso de este Sitio Web &uacute;nicamente para realizar consultas y compras o adquisiciones legalmente v&aacute;lidas.</li>
                    <li>No realizar ninguna compra falsa o fraudulenta. Si razonablemente se pudiera considerar que se ha hecho una compra de esta &iacute;ndole, podr&iacute;a ser anulada y se informar&iacute;a a las autoridades pertinentes.</li>
                    <li>Facilitar datos de contacto veraces y l&iacute;citos, por ejemplo, direcci&oacute;n de correo electr&oacute;nico, direcci&oacute;n postal y/u otros datos (ver Aviso Legal y Condiciones Generales de Uso).</li>
                </ul>
                <p>El Usuario declara ser mayor de 18 a&ntilde;os y tener capacidad legal para celebrar contratos a trav&eacute;s de este Sitio Web.</p>
                <p>El Sitio Web est&aacute; dirigido principalmente a Usuarios residentes en Espa&ntilde;a. Farmacia los llanos no asegura que el Sitio Web cumpla con legislaciones de otros pa&iacute;ses, ya sea total o parcialmente. Farmacia los llanos declina toda responsabilidad que se pueda derivar de dicho acceso, as&iacute; como tampoco asegura env&iacute;os o prestaci&oacute;n de servicios fuera de Espa&ntilde;a.</p>
                <p>El Usuario podr&aacute; formalizar, a su elecci&oacute;n, con Farmacia los llanos el contrato de compraventa de los productos y/o servicios deseados en cualquiera de los idiomas en los que las presentes Condiciones est&eacute;n disponibles en este Sitio Web.</p>
                
                <p><strong>III. PROCESO DE COMPRA O ADQUISICI&Oacute;N</strong></p>
                <p>Los Usuarios pueden comprar en el Sitio Web por los medios y formas establecidos. Deber&aacute;n seguir el procedimiento de compra y/o adquisici&oacute;n online de farmacialosllanos.org, durante el cual varios productos y/o servicios pueden ser seleccionados y a&ntilde;adidos al carrito, cesta o espacio final de compra y, finalmente, hacer clic en "Realizar pedido".</p>
                <p>Asimismo, el Usuario deber&aacute; rellenar y/o comprobar la informaci&oacute;n que en cada paso se le solicita, aunque, durante el proceso de compra, antes de realizar el pago, se pueden modificar los datos de la compra.</p>
                <p>Seguidamente, el Usuario recibir&aacute; un correo electr&oacute;nico confirmando que Farmacia los llanos ha recibido su pedido o solicitud de compra y/o prestaci&oacute;n del servicio, es decir, la confirmaci&oacute;n del pedido. Y, en su caso, se le informar&aacute;, igualmente, mediante correo electr&oacute;nico cuando su compra est&eacute; siendo enviada.</p>
                <p>Una vez el procedimiento de compra ha concluido, el Usuario consiente que el Sitio Web genere una factura electr&oacute;nica que se har&aacute; llegar al Usuario a trav&eacute;s del correo electr&oacute;nico. Asimismo, el Usuario puede, si as&iacute; lo desea, obtener una copia de su factura en papel, solicit&aacute;ndolo a Farmacia los llanos utilizando los espacios de contacto del Sitio Web o a trav&eacute;s de los datos de contacto facilitados m&aacute;s arriba.</p>
                <p>El Usuario reconoce estar al corriente, en el momento de la compra, de ciertas condiciones particulares de venta que conciernen al producto y/o servicio en cuesti&oacute;n y que se muestran junto a la presentaci&oacute;n o, en su caso, imagen de &eacute;ste en su p&aacute;gina del Sitio Web, indicando, a modo enunciativo, pero no exhaustivo, y atendiendo a cada caso: nombre, precio, componentes, peso, cantidad, color, detalles de los productos, o caracter&iacute;sticas, modo en el que se llevar&aacute;n a cabo y/o coste de las prestaciones; y reconoce que la realizaci&oacute;n del pedido de compra o adquisici&oacute;n materializa la aceptaci&oacute;n plena y completa de las condiciones particulares de venta aplicables a cada caso.</p>
                <p>Las comunicaciones, &oacute;rdenes de compra y pagos que intervengan durante las transacciones efectuadas en el Sitio Web podr&iacute;an ser archivadas y conservadas en los registros informatizados de Farmacia los llanos con el fin de constituir un medio de prueba de las transacciones, en todo caso, respetando las condiciones razonables de seguridad y las leyes y normativas vigentes que a este respecto sean de aplicaci&oacute;n, y particularmente atendiendo al Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo, de 27 de abril de 2016, relativo a la protecci&oacute;n de las personas f&iacute;sicas en lo que respecta al tratamiento de datos personales y a la libre circulaci&oacute;n de estos datos (RGPD) y la Ley Org&aacute;nica 3/2018, de 5 de diciembre, de Protecci&oacute;n de Datos Personales y garant&iacute;a de los derechos digitales, y a los derechos que asisten a los Usuarios conforme a la pol&iacute;tica de privacidad de este Sitio Web.</p>
                
                <p><strong>IV. DISPONIBILIDAD</strong></p>
                <p>Todos los pedidos de compra recibidos por Farmacia los llanos a trav&eacute;s del Sitio Web est&aacute;n sujetos a la disponibilidad de los productos y/o a que ninguna circunstancia o causa de fuerza mayor (cl&aacute;usula nueve de estas Condiciones) afecte al suministro de los mismos y/o a la prestaci&oacute;n de los servicios. Si se produjeran dificultades en cuanto al suministro de productos o no quedaran productos en stock, Farmacia los llanos se compromete a contactar al Usuario y reembolsar cualquier cantidad que pudiera haber sido abonada en concepto de importe. Esto ser&aacute; igualmente aplicable en los casos en los que la prestaci&oacute;n de un servicio deviniera irrealizable.</p>
                
                <p><strong>V. PRECIOS Y PAGO</strong></p>
                <p>Los precios exhibidos en el Sitio Web son los finales, en Euros (&euro;) e incluyen los impuestos, salvo que por exigencia legal, especialmente en lo relativo al IVA, se se&ntilde;ale y aplique cuesti&oacute;n distinta.</p>
                <p>Los gastos de env&iacute;o se encuentran incluidos en los precios finales de los productos tal y como se muestran en el Sitio Web. As&iacute;, Farmacia los llanos realiza los servicios de entrega y/o env&iacute;o a trav&eacute;s de: GLS Spain.</p>
                <p>En ning&uacute;n caso el Sitio Web a&ntilde;adir&aacute; costes adicionales al precio de un producto o de un servicio de forma autom&aacute;tica, sino solo aquellos que el Usuario haya seleccionado y elegido voluntaria y libremente.</p>
                <p>Los precios pueden cambiar en cualquier momento, pero los posibles cambios no afectar&aacute;n a los pedidos o compras con respecto a los que el Usuario ya haya recibido una confirmaci&oacute;n de pedido.</p>
                <p>Los medios de pago aceptados ser&aacute;n: PayPal y Transferencia bancaria.</p>
                <p>Farmacia los llanos utiliza todos los medios para garantizar la confidencialidad y la seguridad de los datos de pago transmitidos por el Usuario durante las transacciones a trav&eacute;s del Sitio Web. Como tal, el Sitio Web utiliza un sistema de pago seguro SSL (Secure Socket Layer).</p>
                <p>Si el medio de pago es Paypal el cargo se har&aacute; en el momento en que Farmacia los llanos env&iacute;e una confirmaci&oacute;n del pedido de compra o adquisici&oacute;n de productos y/o servicios al Usuario.</p>
                <p>En todo caso, al hacer clic en "Realizar pedido" el Usuario confirma que el m&eacute;todo de pago utilizado es suyo.</p>
                <p>Los pedidos de compra o adquisici&oacute;n en los que el Usuario seleccione como medio de pago la transferencia bancaria ser&aacute;n reservados durante 5 d&iacute;as naturales a partir de la confirmaci&oacute;n del pedido para poder dejar el tiempo suficiente a que la transferencia bancaria sea tomada en cuenta por el sistema de pagos utilizado por Farmacia los llanos para el Sitio Web. Cuando el sistema recibe la transferencia, el pedido ser&aacute; preparado y gestionado para env&iacute;o.</p>
                <p>Mediante este m&eacute;todo de pago, el Usuario debe asegurarse que introduce correctamente el importe exacto del pedido de compra, as&iacute; como el n&uacute;mero de cuenta y la referencia de la transferencia. En caso de error, Farmacia los llanos no podr&aacute; validar el pedido, que ser&aacute; anulado.</p>
                
                <p><strong>VI. ENTREGA</strong></p>
                <p>En los casos en los que proceda realizar la entrega f&iacute;sica del bien contratado, las entregas se efectuar&aacute;n en el &aacute;mbito del siguiente territorio: Espa&ntilde;a (Pen&iacute;nsula y Baleares).</p>
                <p>Exceptuando aquellos casos en los que existan circunstancias imprevistas o extraordinarias o, en su caso, derivadas de la personalizaci&oacute;n de los productos, el pedido de compra consistente en los productos relacionados en cada confirmaci&oacute;n de compra ser&aacute; entregado en el plazo se&ntilde;alado en el Sitio Web seg&uacute;n el m&eacute;todo de env&iacute;o seleccionado por el Usuario y, en todo caso, en el plazo m&aacute;ximo de 30 d&iacute;as naturales a contar desde la fecha de la confirmaci&oacute;n del pedido.</p>
                <p>Si por alg&uacute;n motivo, que le fuera imputable, Farmacia los llanos no pudiera cumplir con la fecha de entrega, contactar&aacute; al Usuario para informarle de esta circunstancia y, &eacute;ste podr&aacute; elegir seguir adelante con la compra estableciendo una nueva fecha de entrega o bien anular el pedido con el reembolso total del precio pagado. En cualquier caso, las entregas a domicilio se realizan en d&iacute;as laborables.</p>
                <p>Si resultara imposible efectuar la entrega del pedido por ausencia del Usuario, el pedido podr&iacute;a ser devuelto al almac&eacute;n. No obstante, el transportista dejar&iacute;a un aviso explicando d&oacute;nde se encuentra el pedido y c&oacute;mo hacer para que sea entregado de nuevo.</p>
                <p>Si el Usuario no va a estar en el lugar de entrega en la franja horaria convenida, debe ponerse en contacto con Farmacia los llanos para convenir la entrega otro d&iacute;a.</p>
                <p>En caso de que transcurran 30 d&iacute;as desde que su pedido est&eacute; disponible para su entrega, y no haya sido entregado por causa no imputable a Farmacia los llanos, Farmacia los llanos entender&aacute; que el Usuario desea desistir del contrato y &eacute;ste se considerar&aacute; resuelto. Como consecuencia de la resoluci&oacute;n del contrato, todos los pagos recibidos del Usuario le ser&aacute;n devueltos, a excepci&oacute;n de los gastos adicionales resultantes de la elecci&oacute;n propia del Usuario de una modalidad de entrega diferente a la modalidad menos costosa de entrega ordinaria que ofrece el Sitio Web, sin ninguna demora indebida y, en cualquier caso, en el plazo m&aacute;ximo de 14 d&iacute;as naturales desde la fecha en que se considera resuelto el contrato.</p>
                <p>No obstante, el Usuario debe tener presente que el transporte derivado de la resoluci&oacute;n puede tener un coste adicional que le podr&aacute; ser repercutido.</p>
                <p>A efectos de las presentes Condiciones, se entender&aacute; que se ha producido la entrega o que el pedido ha sido entregado en el momento en el que el Usuario o un tercero indicado por el Usuario adquiera la posesi&oacute;n material de los productos, lo que se acreditar&aacute; mediante la firma de la recepci&oacute;n del pedido en la direcci&oacute;n de entrega convenida.</p>
                <p>Los riesgos que de los productos se pudieran derivar ser&aacute;n a cargo del Usuario a partir del momento de su entrega. El Usuario adquiere la propiedad de los productos cuando Farmacia los llanos recibe el pago completo de todas las cantidades debidas en relaci&oacute;n a la compra o adquisici&oacute;n efectuada, incluidos los gastos de env&iacute;o, o bien en el momento de la entrega, si &eacute;sta tiene lugar en un momento posterior a la recepci&oacute;n completa del importe objeto de pago por Farmacia los llanos.</p>
                <p>De conformidad con lo dispuesto en la Ley 37/1992, de 28 de diciembre, del Impuesto sobre el Valor A&ntilde;adido (IVA), los pedidos de compra para su entrega y/o prestaci&oacute;n se entender&aacute;n localizados en el territorio de aplicaci&oacute;n del IVA espa&ntilde;ol si la direcci&oacute;n de entrega est&aacute; en territorio espa&ntilde;ol salvo Canarias, Ceuta y Melilla. El tipo de IVA aplicable ser&aacute; el legalmente vigente en cada momento en funci&oacute;n del art&iacute;culo concreto de que se trate.</p>
                
                <p><strong>VII. MEDIOS T&Eacute;CNICOS PARA CORREGIR ERRORES</strong></p>
                <p>Se pone en conocimiento del Usuario que en caso de que detecte que se ha producido un error al introducir datos necesarios para procesar su solicitud de compra en el Sitio Web, podr&aacute; modificar los mismos poni&eacute;ndose en contacto con Farmacia los llanos a trav&eacute;s de los espacios de contacto habilitados en el Sitio Web, y, en su caso, a trav&eacute;s de aquellos habilitados para contactar con el servicio de atenci&oacute;n al cliente, y/o utilizando los datos de contacto facilitados en la cl&aacute;usula primera (Informaci&oacute;n general).</p>
                <p>En cualquier caso, el Usuario, antes de hacer clic en "Realizar pedido", tiene acceso al espacio, carrito, o cesta donde se van anotando sus solicitudes de compra y puede hacer modificaciones.</p>
                <p>De igual forma, se remite al Usuario a consultar el Aviso Legal y Condiciones Generales de Uso y, en concreto, la Pol&iacute;tica de Privacidad para recabar m&aacute;s informaci&oacute;n sobre c&oacute;mo ejercer su derecho de rectificaci&oacute;n seg&uacute;n lo establecido en el Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo, de 27 de abril de 2016, relativo a la protecci&oacute;n de las personas f&iacute;sicas en lo que respecta al tratamiento de datos personales y a la libre circulaci&oacute;n de estos datos (RGPD) y en la Ley Org&aacute;nica 3/2018, de 5 de diciembre, de Protecci&oacute;n de Datos Personales y garant&iacute;a de los derechos digitales.</p>
                
                <p><strong>VIII. DEVOLUCIONES</strong></p>
                <p>En los casos en los que el Usuario adquiriera productos en o trav&eacute;s del Sitio Web del titular, le asisten una serie de derechos, tal y como se enumeran y describen a continuaci&oacute;n:</p>
                <p><strong>Derecho de Desistimiento</strong></p>
                <p>El Usuario, en tanto que consumidor y usuario, realiza una compra en el Sitio Web y, por tanto le asiste el derecho a desistir de dicha compra en un plazo de 14 d&iacute;as naturales sin necesidad de justificaci&oacute;n.</p>
                <p>Este plazo de desistimiento expirar&aacute; a los 14 d&iacute;as naturales del d&iacute;a que el Usuario o un tercero autorizado por &eacute;ste, distinto del transportista, adquiri&oacute; la posesi&oacute;n material de los bienes adquiridos en el Sitio Web de Farmacia los llanos o en caso de que los bienes que componen su pedido se entreguen por separado, a los 14 d&iacute;as naturales del d&iacute;a que el Usuario o un tercero autorizado por &eacute;ste, distinto del transportista, adquiri&oacute; la posesi&oacute;n material del &uacute;ltimo de esos bienes que compon&iacute;an un mismo pedido de compra, o en el caso de tratarse de un contrato de servicios, a los 14 d&iacute;as naturales desde el d&iacute;a de la celebraci&oacute;n del contrato.</p>
                <p>Para ejercer este derecho de desistimiento, el Usuario deber&aacute; notificar su decisi&oacute;n a Farmacia los llanos. Podr&aacute; hacerlo, en su caso, a trav&eacute;s de los espacios de contacto habilitados en el Sitio Web o a trav&eacute;s de:</p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FARMACIA LOS LLANOS,<br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;con CIF 23242441K,<br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;C/Potasio 7, Loma Cabrera<br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(+34) 950 33 70 53;<br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;contacto@farmacialosllanos.org</p>
                <p>El Usuario, independientemente del medio que elija para comunicar su decisi&oacute;n, debe expresar de forma clara e inequ&iacute;voca que es su intenci&oacute;n desistir del contrato de compra. En todo caso, el Usuario podr&aacute; utilizar el modelo de formulario de desistimiento que Farmacia los llanos pone a su disposici&oacute;n como parte anexada a estas Condiciones, sin embargo, su uso no es obligatorio.</p>
                <p>Para cumplir el plazo de desistimiento, basta con que la comunicaci&oacute;n que expresa inequ&iacute;vocamente la decisi&oacute;n de desistir sea enviada antes de que venza el plazo correspondiente.</p>
                <p>En caso de desistimiento, Farmacia los llanos reembolsar&aacute; al Usuario todos los pagos recibidos, incluidos los gastos de env&iacute;o (con la excepci&oacute;n de los gastos adicionales elegidos por el Usuario para una modalidad de env&iacute;o diferente a la modalidad menos costosa ofrecida en el Sitio Web) sin ninguna demora indebida y, en todo caso, a m&aacute;s tardar en 14 d&iacute;as naturales a partir de la fecha en la que Farmacia los llanos es informado de la decisi&oacute;n de desistir por el Usuario.</p>
                <p>Farmacia los llanos reembolsar&aacute; al Usuario utilizando el mismo m&eacute;todo de pago que emple&oacute; este para realizar la transacci&oacute;n inicial de compra. Este reembolso no generar&aacute; ning&uacute;n coste adicional al Usuario. No obstante, Farmacia los llanos podr&iacute;a retener dicho reembolso hasta haber recibido los productos o art&iacute;culos de la compra, o hasta que el Usuario presente una prueba de la devoluci&oacute;n de los mismos, seg&uacute;n qu&eacute; condici&oacute;n se cumpla primero.</p>
                <p>El Usuario puede devolver o enviar los productos a Farmacia los llanos en:</p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FARMACIA LOS LLANOS,<br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;C/ Potasio 7, Loma Cabrera<br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(+34) 950 33 70 53</p>
                <p>Y deber&aacute; hacerlo sin ninguna demora indebida y, en cualquier caso, a m&aacute;s tardar en el plazo de 14 d&iacute;as naturales a partir de la fecha en que Farmacia los llanos fue informado de la decisi&oacute;n de desistimiento.</p>
                <p>El Usuario reconoce conocer que deber&aacute; asumir el coste directo de devoluci&oacute;n (transporte, entrega) de los bienes, si se incurriera en alguno. Adem&aacute;s, ser&aacute; responsable de la disminuci&oacute;n de valor de los productos resultante de una manipulaci&oacute;n distinta a la necesaria para establecer la naturaleza, las caracter&iacute;sticas y el funcionamiento de los bienes.</p>
                <p>El Usuario reconoce saber que existen excepciones al derecho de desistimiento, tal y como se recoge en el art&iacute;culo 103 del Real Decreto Legislativo 1/2007, de 16 de noviembre, por el que se aprueba el texto refundido de la Ley General para la Defensa de los Consumidores y Usuarios y otras leyes complementarias. De forma enunciativa, y no exhaustiva, este ser&iacute;a el caso de: productos personalizados; productos que puedan deteriorarse o caducar con rapidez; CDs/DVD de m&uacute;sica o video sin su envoltorio, tal y como se precinta en f&aacute;brica; productos que por razones de higiene o de la salud van precintados y han sido desprecintados tras la entrega.</p>
                <p>En este mismo sentido se rige la prestaci&oacute;n de un servicio que el Usuario pudiera contratar en este Sitio Web, pues esta misma Ley establece que no asistir&aacute; el Derecho de desistimiento a los Usuarios cuando la prestaci&oacute;n del servicio ha sido completamente ejecutada, o cuando haya comenzado, con el consentimiento expreso del consumidor y usuario y con el reconocimiento por su parte de que es consciente de que, una vez que el contrato haya sido completamente ejecutado por Farmacia los llanos, habr&aacute; perdido su derecho de desistimiento.</p>
                <p>En todo caso, no se har&aacute; ning&uacute;n reembolso si el producto ha sido usado m&aacute;s all&aacute; de la mera apertura del mismo, de productos que no est&eacute;n en las mismas condiciones en las que se entregaron o que hayan sufrido alg&uacute;n da&ntilde;o tras la entrega.</p>
                <p>Asimismo, se debe devolver los productos usando o incluyendo todos sus envoltorios originales, las instrucciones y dem&aacute;s documentos que en su caso los acompa&ntilde;en, adem&aacute;s de una copia de la factura de compra.</p>
                <p>En el siguiente enlace puede descargarse el Modelo de formulario de desistimiento:</p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://farmacialosllanos.org/contact">https://farmacialosllanos.org/contact</a></p>
                <p><strong>Devoluci&oacute;n de productos defectuosos o error en el env&iacute;o</strong></p>
                <p>Se trata de todos aquellos casos en los que el Usuario considera que, en el momento de la entrega, el producto no se ajusta a lo estipulado en el contrato o pedido de compra, y que, por tanto, deber&aacute; ponerse en contacto con Farmacia los llanos inmediatamente y hacerle saber la disconformidad existente (defecto/error) por los mismos medios o utilizando los datos de contacto que se facilitan en el apartado anterior (Derecho de Desistimiento).</p>
                <p>El Usuario ser&aacute; entonces informado sobre c&oacute;mo proceder a la devoluci&oacute;n de los productos, y estos, una vez devueltos, ser&aacute;n examinados y se informar&aacute; al Usuario, dentro de un plazo razonable, si procede el reembolso o, en su caso, la sustituci&oacute;n del mismo.</p>
                <p>El reembolso o la sustituci&oacute;n del producto se efectuar&aacute; lo antes posible y, en cualquier caso, dentro de los 14 d&iacute;as siguientes a la fecha en la que le enviemos un correo electr&oacute;nico confirmando que procede el reembolso o la sustituci&oacute;n del art&iacute;culo no conforme.</p>
                <p>El importe abonado por aquellos productos que sean devueltos a causa de alg&uacute;n defecto, cuando realmente exista, ser&aacute; reembolsado &iacute;ntegramente, incluidos los gastos de entrega y los costes en que hubiera podido incurrir el Usuario para realizar la devoluci&oacute;n. El reembolso se efectuar&aacute; por el mismo medio de pago que el Usuario utiliz&oacute; para pagar la compra.</p>
                <p>En todo caso, se estar&aacute; siempre a los derechos reconocidos en la legislaci&oacute;n vigente en cada momento para el Usuario, en tanto que consumidor y usuario.</p>
                <p><strong>Garant&iacute;as</strong></p>
                <p>El Usuario, en tanto que consumidor y usuario, goza de garant&iacute;as sobre los productos que pueda adquirir a trav&eacute;s de este Sitio Web, en los t&eacute;rminos legalmente establecidos para cada tipo de producto, respondiendo Farmacia los llanos, por tanto, por la falta de conformidad de los mismos que se manifieste en un plazo de dos a&ntilde;os desde la entrega del producto.</p>
                <p>En este sentido, se entiende que los productos son conformes con el contrato siempre que: se ajusten a la descripci&oacute;n realizada por Farmacia los llanos y posean las cualidades presentadas en la misma; sean aptos para los usos a que ordinariamente se destinan los productos del mismo tipo; y presenten la calidad y prestaciones habituales de un producto del mismo tipo y que sean fundamentalmente esperables del mismo. Cuando esto no sea as&iacute; respecto de los productos entregados al Usuario, &eacute;ste deber&aacute; proceder tal y como se indica en el apartado Devoluci&oacute;n de productos defectuosos o error en el env&iacute;o. No obstante, algunos de los productos que se comercializan en el Sitio Web, podr&iacute;an presentar caracter&iacute;sticas no homog&eacute;neas siempre y cuando &eacute;stas deriven del tipo de material con el que se han fabricado, y que por ende formar&aacute;n parte de la apariencia individual del producto, y no ser&aacute;n un defecto.</p>
                <p>Por otra parte, podr&iacute;a llegar a darse el caso que el Usuario adquiere en el Sitio Web un producto de una marca o de fabricaci&oacute;n por un tercero. En este caso, y considerando el Usuario que se trata de un producto defectuoso, &eacute;ste tambi&eacute;n tiene la posibilidad de ponerse en contacto con la marca o fabricante responsable del producto para averiguar c&oacute;mo ejercer su derecho de garant&iacute;a legal directamente frente a los mismos durante los dos a&ntilde;os siguientes a la entrega de dichos productos. Para ello, el Usuario debe haber conservado toda la informaci&oacute;n en relaci&oacute;n con la garant&iacute;a de los productos.</p>
                
                <p><strong>IX. EXONERACI&Oacute;N DE RESPONSABILIDAD</strong></p>
                <p>Salvo disposici&oacute;n legal en sentido contrario, Farmacia los llanos no aceptar&aacute; ninguna responsabilidad por las siguientes p&eacute;rdidas, con independencia de su origen:</p>
                <ul>
                    <li>cualesquiera p&eacute;rdidas que no fueran atribuibles a incumplimiento alguno por su parte;</li>
                    <li>p&eacute;rdidas empresariales (incluyendo lucro cesante, de ingresos, de contratos, de ahorros previstos, de datos, p&eacute;rdida del fondo de comercio o gastos innecesarios incurridos); o de</li>
                    <li>toda otra p&eacute;rdida indirecta que no fuera razonablemente previsible por ambas partes en el momento en que se formaliz&oacute; el contrato de compraventa de los productos entre ambas partes.</li>
                </ul>
                <p>Igualmente, Farmacia los llanos tambi&eacute;n limita su responsabilidad en cuanto a los siguientes casos:</p>
                <ul>
                    <li>Farmacia los llanos aplica todas las medidas concernientes a proporcionar una visualizaci&oacute;n fiel del producto en el Sitio Web, sin embargo no se responsabiliza por las m&iacute;nimas diferencias o inexactitudes que puedan existir debido a falta de resoluci&oacute;n de la pantalla, o problemas del navegador que se utilice u otros de esta &iacute;ndole.</li>
                    <li>Farmacia los llanos actuar&aacute; con la m&aacute;xima diligencia a efectos de poner a disposici&oacute;n de la empresa encargada del transporte del producto objeto del pedido de compra. Sin embargo, no se responsabiliza por perjuicios provenientes de un mal funcionamiento del transporte, especialmente por causas como huelgas, retenciones en carreteras, y en general cualquiera otras propias del sector, que deriven en retrasos, p&eacute;rdidas o hurtos del producto.</li>
                    <li>Fallos t&eacute;cnicos que por causas fortuitas o de otra &iacute;ndole, impidan un normal funcionamiento del servicio a trav&eacute;s de internet. Falta de disponibilidad del Sitio Web por razones de mantenimiento u otras, que impida disponer del servicio. Farmacia los llanos pone todos los medios a su alcance a efectos de llevar a cabo el proceso de compra, pago y env&iacute;o/entrega de los productos, no obstante se exime de responsabilidad por causas que no le sean imputables, caso fortuito o fuerza mayor.</li>
                    <li>Farmacia los llanos no se har&aacute; responsable del mal uso y/o del desgaste de los productos que hayan sido utilizados por el Usuario. Al mismo tiempo, Farmacia los llanos tampoco se har&aacute; responsable de una devoluci&oacute;n err&oacute;nea realizada por el Usuario. Es responsabilidad del Usuario devolver el producto correcto.</li>
                    <li>En general, Farmacia los llanos no se responsabilizar&aacute; por ning&uacute;n incumplimiento o retraso en el cumplimiento de alguna de las obligaciones asumidas, cuando el mismo se deba a acontecimientos que est&aacute;n fuera de su control razonable, es decir, que se deban a causa de fuerza mayor, y &eacute;sta podr&aacute; incluir, a modo enunciativo pero no exhaustivo:</li>
                    <ul>
                        <li>Huelgas, cierres patronales u otras medidas reivindicativas.</li>
                        <li>Conmoci&oacute;n civil, revuelta, invasi&oacute;n, amenaza o ataque terrorista, guerra (declarada o no) o amenaza o preparativos de guerra.</li>
                        <li>Incendio, explosi&oacute;n, tormenta, inundaci&oacute;n, terremoto, hundimiento, epidemia o cualquier otro desastre natural.</li>
                        <li>Imposibilidad de uso de trenes, barcos, aviones, transportes de motor u otros medios de transporte, p&uacute;blicos o privados.</li>
                        <li>Imposibilidad de utilizar sistemas p&uacute;blicos o privados de telecomunicaciones.</li>
                        <li>Actos, decretos, legislaci&oacute;n, normativa o restricciones de cualquier gobierno o autoridad p&uacute;blica.</li>
                    </ul>
                </ul>
                <p>De esta forma, las obligaciones quedar&aacute;n suspendidas durante el periodo en que la causa de fuerza mayor contin&uacute;e, y Farmacia los llanos dispondr&aacute; de una ampliaci&oacute;n en el plazo para cumplirlas por un periodo de tiempo igual al que dure la causa de fuerza mayor. Farmacia los llanos pondr&aacute; todos los medios razonables para encontrar una soluci&oacute;n que le permita cumplir con sus obligaciones a pesar de la causa de fuerza mayor.</p>
                
                <p><strong>X. COMUNICACIONES POR ESCRITO Y NOTIFICACIONES</strong></p>
                <p>Mediante el uso de este Sitio Web, el Usuario acepta que la mayor parte de las comunicaciones con Farmacia los llanos sean electr&oacute;nicas (correo electr&oacute;nico o avisos publicados en el Sitio Web).</p>
                <p>A efectos contractuales, el Usuario consiente en usar este medio electr&oacute;nico de comunicaci&oacute;n y reconoce que todo contrato, notificaci&oacute;n, informaci&oacute;n y dem&aacute;s comunicaciones que Farmacia los llanos env&iacute;e de forma electr&oacute;nica cumplen con los requisitos legales de ser por escrito. Esta condici&oacute;n no afectar&aacute; a los derechos reconocidos por ley al Usuario.</p>
                <p>El Usuario puede enviar notificaciones y/o comunicarse con Farmacia los llanos a trav&eacute;s de los datos de contacto que en estas Condiciones se facilitan y, en su caso, a trav&eacute;s de los espacios de contacto del Sitio Web.</p>
                <p>Igualmente, salvo que se estipule lo contrario, Farmacia los llanos puede contactar y/o notificar al Usuario en su correo electr&oacute;nico o en la direcci&oacute;n postal facilitada.</p>
                
                <p><strong>XI. RENUNCIA</strong></p>
                <p>Ninguna renuncia de Farmacia los llanos a un derecho o acci&oacute;n legal concreta o la falta de requerimiento por Farmacia los llanos del cumplimiento estricto por el Usuario de alguna de sus obligaciones supondr&aacute;, ni una renuncia a otros derechos o acciones derivados de un contrato o de las Condiciones, ni exonerar&aacute; al Usuario del cumplimiento de sus obligaciones.</p>
                <p>Ninguna renuncia de Farmacia los llanos a alguna de las presentes Condiciones o a los derechos o acciones derivados de un contrato surtir&aacute; efecto, a no ser que se establezca expresamente que es una renuncia y se formalice y se le comunique al Usuario por escrito.</p>
                
                <p><strong>XII. NULIDAD</strong></p>
                <p>Si alguna de las presentes Condiciones fuesen declaradas nulas y sin efecto por resoluci&oacute;n firme dictada por autoridad competente, el resto de las cl&aacute;usulas permanecer&aacute;n en vigor, sin que queden afectadas por dicha declaraci&oacute;n de nulidad.</p>
                
                <p><strong>XIII. ACUERDO COMPLETO</strong></p>
                <p>Las presentes Condiciones y todo documento al que se haga referencia expresa en estas constituyen el acuerdo &iacute;ntegro existente entre el Usuario y Farmacia los llanos en relaci&oacute;n con el objeto de compraventa y sustituyen a cualquier otro pacto, acuerdo o promesa anterior convenida verbalmente o por escrito por las mismas partes.</p>
                <p>El Usuario y Farmacia los llanos reconocen haber consentido la celebraci&oacute;n de un contrato sin haber confiado en ninguna declaraci&oacute;n o promesa hecha por la otra parte, salvo aquello que figura expresamente mencionado en las presentes Condiciones.</p>
                
                <p><strong>XIV. PROTECCI&Oacute;N DE DATOS</strong></p>
                <p>La informaci&oacute;n o datos de car&aacute;cter personal que el Usuario facilite a Farmacia los llanos en el curso de una transacci&oacute;n en el Sitio Web, ser&aacute;n tratados con arreglo a lo establecido en la Pol&iacute;tica de Privacidad o de protecci&oacute;n de datos (contenida, en su caso, en el Aviso Legal y Condiciones Generales de Uso). Al acceder, navegar y/o usar el Sitio Web el Usuario consiente el tratamiento de dicha informaci&oacute;n y datos y declara que toda la informaci&oacute;n o datos que facilita son veraces.</p>
                
                <p><strong>XV. LEGISLACI&Oacute;N APLICABLE Y JURISDICCI&Oacute;N</strong></p>
                <p>El acceso, navegaci&oacute;n y/o uso de este Sitio Web y los contratos de compra de productos a trav&eacute;s del mismo se regir&aacute;n por la legislaci&oacute;n espa&ntilde;ola.</p>
                <p>Cualquier controversia, problema o desacuerdo que surja o est&eacute; relacionado con el acceso, navegaci&oacute;n y/o uso del Sitio Web, o con la interpretaci&oacute;n y ejecuci&oacute;n de estas Condiciones, o con los contratos de venta entre Farmacia los llanos y el Usuario, ser&aacute; sometida a la jurisdicci&oacute;n no exclusiva de los juzgados y tribunales espa&ntilde;oles.</p>
                
                <p><strong>XVI. QUEJAS Y RECLAMACIONES</strong></p>
                <p>El Usuario puede hacer llegar a Farmacia los llanos sus quejas, reclamaciones o todo otro comentario que desee realizar a trav&eacute;s de los datos de contacto que se facilitan al principio de estas Condiciones (Informaci&oacute;n General).</p>
                <p>Adem&aacute;s, Farmacia los llanos dispone de hojas oficiales de reclamaci&oacute;n a disposici&oacute;n de los consumidores y usuarios, y que estos pueden solicitar a Farmacia los llanos en cualquier momento, utilizando los datos de contacto que se facilitan al principio de estas Condiciones (Informaci&oacute;n General).</p>
                
                <p>&Uacute;ltima modificaci&oacute;n: 3 de mayo 2021</p>
            </div>
        </div>
    </div>

    <?php sectioncookies($trans);?>
    <?php sectionfooter($trans);?>

    <?php sectionjs();?>
</body>