<!DOCTYPE html>
<?php include ("./controller/main.php");?>
<html class="no-js" lang="<?=$lang?>">
<head>
    <?php sectionhead($db)?>
</head>

<body>
    <?php sectiontopbar($trans);?>

    <?php sectionheader($db, 0, $trans); ?>

    <?php sectionbreadcrumb('|termsandconditions', $trans);?>

    <div class="section section-padding">
        <div class="container">
            <div class="section-title3">
                <p><strong>I. INFORMACI&Oacute;N GENERAL</strong></p>
                <p>En cumplimiento con el deber de informaci&oacute;n dispuesto en la Ley 34/2002 de Servicios de la Sociedad de la Informaci&oacute;n y el Comercio Electr&oacute;nico (LSSI-CE) de 11 de julio, se facilitan a continuaci&oacute;n los siguientes datos de informaci&oacute;n general de este sitio web:</p>
                <p>La titularidad de este sitio web, farmacialosllanos.org, (en adelante, Sitio Web) la ostenta: FARMACIA LOS LLANOS, provista de NIF: 23242441K e inscrita en: Registro Mercantil de la provincia de Almer&iacute;a con los siguientes datos registrales: Tomo 2095; Folio 10, inscripci&oacute;n 1&ordm;, Hoja Al-58275, cuyo representante es: Victor Manuel Manrique Morales, y cuyos datos de contacto son:</p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Direcci&oacute;n: C/ Potasio 7, Loma Cabrera<br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tel&eacute;fono de contacto: (+34) 950 33 70 53<br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Email de contacto: contacto@farmacialosllanos.org</p>

                <p><strong>II. T&Eacute;RMINOS Y CONDICIONES GENERALES DE USO</strong></p>
                <p><strong>El objeto de las condiciones: El Sitio Web</strong></p>
                <p>El objeto de las presentes Condiciones Generales de Uso (en adelante, Condiciones) es regular el acceso y la utilizaci&oacute;n del Sitio Web. A los efectos de las presentes Condiciones se entender&aacute; como Sitio Web: la apariencia externa de los interfaces de pantalla, tanto de forma est&aacute;tica como de forma din&aacute;mica, es decir, el &aacute;rbol de navegaci&oacute;n; y todos los elementos integrados tanto en los interfaces de pantalla como en el &aacute;rbol de navegaci&oacute;n (en adelante, Contenidos) y todos aquellos servicios o recursos en l&iacute;nea que en su caso ofrezca a los Usuarios (en adelante, Servicios).</p>
                <p>Farmacia los llanos se reserva la facultad de modificar, en cualquier momento, y sin aviso previo, la presentaci&oacute;n y configuraci&oacute;n del Sitio Web y de los Contenidos y Servicios que en &eacute;l pudieran estar incorporados. El Usuario reconoce y acepta que en cualquier momento Farmacia los llanos pueda interrumpir, desactivar y/o cancelar cualquiera de estos elementos que se integran en el Sitio Web o el acceso a los mismos.</p>
                <p>El acceso al Sitio Web por el Usuario tiene car&aacute;cter libre y, por regla general, es gratuito sin que el Usuario tenga que proporcionar una contraprestaci&oacute;n para poder disfrutar de ello, salvo en lo relativo al coste de conexi&oacute;n a trav&eacute;s de la red de telecomunicaciones suministrada por el proveedor de acceso que hubiere contratado el Usuario.</p>
                <p>La utilizaci&oacute;n de alguno de los Contenidos o Servicios del Sitio Web podr&aacute; hacerse mediante la suscripci&oacute;n o registro previo del Usuario.</p>
                <p><strong>El Usuario</strong></p>
                <p>El acceso, la navegaci&oacute;n y uso del Sitio Web, as&iacute; como por los espacios habilitados para interactuar entre los Usuarios, y el Usuario y Farmacia los llanos, como los comentarios y/o espacios de blogging, confiere la condici&oacute;n de Usuario, por lo que se aceptan, desde que se inicia la navegaci&oacute;n por el Sitio Web, todas las Condiciones aqu&iacute; establecidas, as&iacute; como sus ulteriores modificaciones, sin perjuicio de la aplicaci&oacute;n de la correspondiente normativa legal de obligado cumplimiento seg&uacute;n el caso. Dada la relevancia de lo anterior, se recomienda al Usuario leerlas cada vez que visite el Sitio Web.</p>
                <p>El Sitio Web de Farmacia los llanos proporciona gran diversidad de informaci&oacute;n, servicios y datos. El Usuario asume su responsabilidad para realizar un uso correcto del Sitio Web. Esta responsabilidad se extender&aacute; a:</p>
                <ul>
                    <li>Un uso de la informaci&oacute;n, Contenidos y/o Servicios y datos ofrecidos por Farmacia los llanos sin que sea contrario a lo dispuesto por las presentes Condiciones, la Ley, la moral o el orden p&uacute;blico, o que de cualquier otro modo puedan suponer lesi&oacute;n de los derechos de terceros o del mismo funcionamiento del Sitio Web.</li>
                    <li>La veracidad y licitud de las informaciones aportadas por el Usuario en los formularios extendidos por Farmacia los llanos para el acceso a ciertos Contenidos o Servicios ofrecidos por el Sitio Web. En todo caso, el Usuario notificar&aacute; de forma inmediata a Farmacia los llanos acerca de cualquier hecho que permita el uso indebido de la informaci&oacute;n registrada en dichos formularios, tales como, pero no s&oacute;lo, el robo, extrav&iacute;o, o el acceso no autorizado a identificadores y/o contrase&ntilde;as, con el fin de proceder a su inmediata cancelaci&oacute;n.</li>
                </ul>
                <p>Farmacia los llanos se reserva el derecho de retirar todos aquellos comentarios y aportaciones que vulneren la ley, el respeto a la dignidad de la persona, que sean discriminatorios, xen&oacute;fobos, racistas, pornogr&aacute;ficos, spamming, que atenten contra la juventud o la infancia, el orden o la seguridad p&uacute;blica o que, a su juicio, no resultaran adecuados para su publicaci&oacute;n.</p>
                <p>En cualquier caso, Farmacia los llanos no ser&aacute; responsable de las opiniones vertidas por los Usuarios a trav&eacute;s de comentarios u otras herramientas de blogging o de participaci&oacute;n que pueda haber.</p>
                <p>El mero acceso a este Sitio Web no supone entablar ning&uacute;n tipo de relaci&oacute;n de car&aacute;cter comercial entre Farmacia los llanos y el Usuario.</p>
                <p>El Usuario declara ser mayor de edad y disponer de la capacidad jur&iacute;dica suficiente para vincularse por las presentes Condiciones. Por lo tanto, este Sitio Web de Farmacia los llanos no se dirige a menores de edad. Farmacia los llanos declina cualquier responsabilidad por el incumplimiento de este requisito.</p>
                <p>El Sitio Web est&aacute; dirigido principalmente a Usuarios residentes en Espa&ntilde;a. Farmacia los llanos no asegura que el Sitio Web cumpla con legislaciones de otros pa&iacute;ses, ya sea total o parcialmente. Si el Usuario reside o tiene su domiciliado en otro lugar y decide acceder y/o navegar en el Sitio Web lo har&aacute; bajo su propia responsabilidad, deber&aacute; asegurarse de que tal acceso y navegaci&oacute;n cumple con la legislaci&oacute;n local que le es aplicable, no asumiendo Farmacia los llanos responsabilidad alguna que se pueda derivar de dicho acceso.</p>

                <p><strong> III. ACCESO Y NAVEGACI&Oacute;N EN EL SITIO WEB: EXCLUSI&Oacute;N DE GARANT&Iacute;AS Y RESPONSABILIDAD</strong></p>
                <p>Farmacia los llanos no garantiza la continuidad, disponibilidad y utilidad del Sitio Web, ni de los Contenidos o Servicios. Farmacia los llanos har&aacute; todo lo posible por el buen funcionamiento del Sitio Web, sin embargo, no se responsabiliza ni garantiza que el acceso a este Sitio Web no vaya a ser ininterrumpido o que est&eacute; libre de error.</p>
                <p>Tampoco se responsabiliza o garantiza que el contenido o software al que pueda accederse a trav&eacute;s de este Sitio Web, est&eacute; libre de error o cause un da&ntilde;o al sistema inform&aacute;tico (software y hardware) del Usuario. En ning&uacute;n caso Farmacia los llanos ser&aacute; responsable por las p&eacute;rdidas, da&ntilde;os o perjuicios de cualquier tipo que surjan por el acceso, navegaci&oacute;n y el uso del Sitio Web, incluy&eacute;ndose, pero no limit&aacute;ndose, a los ocasionados a los sistemas inform&aacute;ticos o los provocados por la introducci&oacute;n de virus.</p>
                <p>Farmacia los llanos tampoco se hace responsable de los da&ntilde;os que pudiesen ocasionarse a los usuarios por un uso inadecuado de este Sitio Web. En particular, no se hace responsable en modo alguno de las ca&iacute;das, interrupciones, falta o defecto de las telecomunicaciones que pudieran ocurrir.</p>

                <p><strong>IV. POL&Iacute;TICA DE PRIVACIDAD Y PROTECCI&Oacute;N DE DATOS</strong></p>
                <p>Respetando lo establecido en la legislaci&oacute;n vigente, Farmacia los llanos se compromete a adoptar las medidas t&eacute;cnicas y organizativas necesarias, seg&uacute;n el nivel de seguridad adecuado al riesgo de los datos recogidos.</p>
                <p><strong>Leyes que incorpora esta pol&iacute;tica de privacidad</strong></p>
                <p>Esta pol&iacute;tica de privacidad est&aacute; adaptada a la normativa espa&ntilde;ola y europea vigente en materia de protecci&oacute;n de datos personales en internet. En concreto, la misma respeta las siguientes normas:</p>
                <ul>
                    <li>El Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo, de 27 de abril de 2016, relativo a la protecci&oacute;n de las personas f&iacute;sicas en lo que respecta al tratamiento de datos personales y a la libre circulaci&oacute;n de estos datos (RGPD).</li>
                    <li>La Ley Org&aacute;nica 3/2018, de 5 de diciembre, de Protecci&oacute;n de Datos Personales y garant&iacute;a de los derechos digitales (LOPD-GDD).</li>
                    <li>El Real Decreto 1720/2007, de 21 de diciembre, por el que se aprueba el Reglamento de desarrollo de la Ley Org&aacute;nica 15/1999, de 13 de diciembre, de Protecci&oacute;n de Datos de Car&aacute;cter Personal (RDLOPD).</li>
                    <li>La Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Informaci&oacute;n y de Comercio Electr&oacute;nico (LSSI-CE).</li>
                </ul>
                <p><strong>Identidad del responsable del tratamiento de los datos personales</strong></p>
                <p>El responsable del tratamiento de los datos personales recogidos en Farmacia los llanos es: FARMACIA LOS LLANOS, provista de NIF: 23242441K e inscrita en: Registro Mercantil de la provincia de Almer&iacute;a con los siguientes datos registrales: Tomo 2095; Folio 10, inscripci&oacute;n 1&ordm;, Hoja Al-58275, cuyo representante es: Victor Manuel Manrique Morales (en adelante, tambi&eacute;n Responsable del tratamiento). Sus datos de contacto son los siguientes:</p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Direcci&oacute;n: C/ Potasio 7, Loma Cabrera<br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tel&eacute;fono de contacto: (+34) 950 33 70 53<br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Email de contacto: contacto@farmacialosllanos.org</p>
                <p><strong>Delegado de Protecci&oacute;n de Datos (DPD)</strong></p>
                <p>El Delegado de Protecci&oacute;n de Datos (DPD, o DPO por sus siglas en ingl&eacute;s) es el encargado de velar por el cumplimiento de la normativa de protecci&oacute;n de datos a la cual se encuentra sujeta Farmacia los llanos. El Usuario puede contactar con el DPD designado por el Responsable del tratamiento utilizando los siguientes datos de contacto: acformed@acformed.org; 653051539.</p>
                <p><strong>Registro de Datos de Car&aacute;cter Personal</strong></p>
                <p>En cumplimiento de lo establecido en el RGPD y la LOPD-GDD, le informamos que los datos personales recabados por Farmacia los llanos mediante los formularios extendidos en sus p&aacute;ginas quedar&aacute;n incorporados y ser&aacute;n tratados en nuestro ficheros con el fin de poder facilitar, agilizar y cumplir los compromisos establecidos entre Farmacia los llanos y el Usuario o el mantenimiento de la relaci&oacute;n que se establezca en los formularios que este rellene, o para atender una solicitud o consulta del mismo. Asimismo, de conformidad con lo previsto en el RGPD y la LOPD-GDD, salvo que sea de aplicaci&oacute;n la excepci&oacute;n prevista en el art&iacute;culo 30.5 del RGPD, se mantiene un registro de actividades de tratamiento que especifica, seg&uacute;n sus finalidades, las actividades de tratamiento llevadas a cabo y las dem&aacute;s circunstancias establecidas en el RGPD.</p>
                <p><strong>Principios aplicables al tratamiento de los datos personales</strong></p>
                <p>El tratamiento de los datos personales del Usuario se someter&aacute; a los siguientes principios recogidos en el art&iacute;culo 5 del RGPD:</p>
                <ul>
                    <li>Principio de licitud, lealtad y transparencia: se requerir&aacute; en todo momento el consentimiento del Usuario previa informaci&oacute;n completamente transparente de los fines para los cuales se recogen los datos personales.</li>
                    <li>Principio de limitaci&oacute;n de la finalidad: los datos personales ser&aacute;n recogidos con fines determinados, expl&iacute;citos y leg&iacute;timos.</li>
                    <li>Principio de minimizaci&oacute;n de datos: los datos personales recogidos ser&aacute;n &uacute;nicamente los estrictamente necesarios en relaci&oacute;n con los fines para los que son tratados.</li>
                    <li>Principio de exactitud: los datos personales deben ser exactos y estar siempre actualizados.</li>
                    <li>Principio de limitaci&oacute;n del plazo de conservaci&oacute;n: los datos personales solo ser&aacute;n mantenidos de forma que se permita la identificaci&oacute;n del Usuario durante el tiempo necesario para los fines de su tratamiento.</li>
                    <li>Principio de integridad y confidencialidad: los datos personales ser&aacute;n tratados de manera que se garantice su seguridad y confidencialidad.</li>
                    <li>Principio de responsabilidad proactiva: el Responsable del tratamiento ser&aacute; responsable de asegurar que los principios anteriores se cumplen.</li>
                </ul>
                <p><strong>Categor&iacute;as de datos personales</strong></p>
                <p>Las categor&iacute;as de datos que se tratan en Farmacia los llanos son &uacute;nicamente datos identificativos. En ning&uacute;n caso, se tratan categor&iacute;as especiales de datos personales en el sentido del art&iacute;culo 9 del RGPD.</p>
                <p><strong>Base legal para el tratamiento de los datos personales</strong></p>
                <p>La base legal para el tratamiento de los datos personales es el consentimiento. Farmacia los llanos se compromete a recabar el consentimiento expreso y verificable del Usuario para el tratamiento de sus datos personales para uno o varios fines espec&iacute;ficos.</p>
                <p>El Usuario tendr&aacute; derecho a retirar su consentimiento en cualquier momento. Ser&aacute; tan f&aacute;cil retirar el consentimiento como darlo. Como regla general, la retirada del consentimiento no condicionar&aacute; el uso del Sitio Web.</p>
                <p>En las ocasiones en las que el Usuario deba o pueda facilitar sus datos a trav&eacute;s de formularios para realizar consultas, solicitar informaci&oacute;n o por motivos relacionados con el contenido del Sitio Web, se le informar&aacute; en caso de que la cumplimentaci&oacute;n de alguno de ellos sea obligatoria debido a que los mismos sean imprescindibles para el correcto desarrollo de la operaci&oacute;n realizada.</p>
                <p><strong>Fines del tratamiento a que se destinan los datos personales</strong></p>
                <p>Los datos personales son recabados y gestionados por Farmacia los llanos con la finalidad de poder facilitar, agilizar y cumplir los compromisos establecidos entre el Sitio Web y el Usuario o el mantenimiento de la relaci&oacute;n que se establezca en los formularios que este &uacute;ltimo rellene o para atender una solicitud o consulta.</p>
                <p>Igualmente, los datos podr&aacute;n ser utilizados con una finalidad comercial de personalizaci&oacute;n, operativa y estad&iacute;stica, y actividades propias del objeto social de Farmacia los llanos, as&iacute; como para la extracci&oacute;n, almacenamiento de datos y estudios de marketing para adecuar el Contenido ofertado al Usuario, as&iacute; como mejorar la calidad, funcionamiento y navegaci&oacute;n por el Sitio Web.</p>
                <p>En el momento en que se obtengan los datos personales, se informar&aacute; al Usuario acerca del fin o fines espec&iacute;ficos del tratamiento a que se destinar&aacute;n los datos personales; es decir, del uso o usos que se dar&aacute; a la informaci&oacute;n recopilada.</p>
                <p><strong>Per&iacute;odos de retenci&oacute;n de los datos personales</strong></p>
                <p>Los datos personales solo ser&aacute;n retenidos durante el tiempo m&iacute;nimo necesario para los fines de su tratamiento y, en todo caso, &uacute;nicamente durante el siguiente plazo: 2 a&ntilde;os, o hasta que el Usuario solicite su supresi&oacute;n.</p>
                <p>En el momento en que se obtengan los datos personales, se informar&aacute; al Usuario acerca del plazo durante el cual se conservar&aacute;n los datos personales o, cuando eso no sea posible, los criterios utilizados para determinar este plazo.</p>
                <p><strong>Destinatarios de los datos personales</strong></p>
                <p>Los datos personales del Usuario ser&aacute;n compartidos con los siguientes destinatarios o categor&iacute;as de destinatarios:</p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Soluciones Web Online, S.L. con domicilio social Calle Hermanos Machado, 19, CP 04720 EL PARADOR, Almer&iacute;a</p>
                <p>En caso de que el Responsable del tratamiento tenga la intenci&oacute;n de transferir datos personales a un tercer pa&iacute;s u organizaci&oacute;n internacional, en el momento en que se obtengan los datos personales, se informar&aacute; al Usuario acerca del tercer pa&iacute;s u organizaci&oacute;n internacional al cual se tiene la intenci&oacute;n de transferir los datos, as&iacute; como de la existencia o ausencia de una decisi&oacute;n de adecuaci&oacute;n de la Comisi&oacute;n.</p>
                <p><strong>Datos personales de menores de edad</strong></p>
                <p>Respetando lo establecido en los art&iacute;culos 8 del RGPD y 13 del RDLOPD, solo los mayores de 14 a&ntilde;os podr&aacute;n otorgar su consentimiento para el tratamiento de sus datos personales de forma l&iacute;cita por Farmacia los llanos. Si se trata de un menor de 14 a&ntilde;os, ser&aacute; necesario el consentimiento de los padres o tutores para el tratamiento, y este solo se considerar&aacute; l&iacute;cito en la medida en la que los mismos lo hayan autorizado.</p>
                <p><strong>Secreto y seguridad de los datos personales</strong></p>
                <p>Farmacia los llanos se compromete a adoptar las medidas t&eacute;cnicas y organizativas necesarias, seg&uacute;n el nivel de seguridad adecuado al riesgo de los datos recogidos, de forma que se garantice la seguridad de los datos de car&aacute;cter personal y se evite la destrucci&oacute;n, p&eacute;rdida o alteraci&oacute;n accidental o il&iacute;cita de datos personales transmitidos, conservados o tratados de otra forma, o la comunicaci&oacute;n o acceso no autorizados a dichos datos.</p>
                <p>El Sitio Web cuenta con un certificado SSL (Secure Socket Layer), que asegura que los datos personales se transmiten de forma segura y confidencial, al ser la transmisi&oacute;n de los datos entre el servidor y el Usuario, y en retroalimentaci&oacute;n, totalmente cifrada o encriptada.</p>
                <p>Sin embargo, debido a que Farmacia los llanos no puede garantizar la inexpugnabilidad de internet ni la ausencia total de hackers u otros que accedan de modo fraudulento a los datos personales, el Responsable del tratamiento se compromete a comunicar al Usuario sin dilaci&oacute;n indebida cuando ocurra una violaci&oacute;n de la seguridad de los datos personales que sea probable que entra&ntilde;e un alto riesgo para los derechos y libertades de las personas f&iacute;sicas. Siguiendo lo establecido en el art&iacute;culo 4 del RGPD, se entiende por violaci&oacute;n de la seguridad de los datos personales toda violaci&oacute;n de la seguridad que ocasione la destrucci&oacute;n, p&eacute;rdida o alteraci&oacute;n accidental o il&iacute;cita de datos personales transmitidos, conservados o tratados de otra forma, o la comunicaci&oacute;n o acceso no autorizados a dichos datos.</p>
                <p>Los datos personales ser&aacute;n tratados como confidenciales por el Responsable del tratamiento, quien se compromete a informar de y a garantizar por medio de una obligaci&oacute;n legal o contractual que dicha confidencialidad sea respetada por sus empleados, asociados, y toda persona a la cual le haga accesible la informaci&oacute;n.</p>
                <p><strong>Derechos derivados del tratamiento de los datos personales</strong></p>
                <p>El Usuario tiene sobre Farmacia los llanos y podr&aacute;, por tanto, ejercer frente al Responsable del tratamiento los siguientes derechos reconocidos en el RGPD:</p>
                <ul>
                    <li><em>Derecho de acceso</em>: Es el derecho del Usuario a obtener confirmaci&oacute;n de si Farmacia los llanos est&aacute; tratando o no sus datos personales y, en caso afirmativo, obtener informaci&oacute;n sobre sus datos concretos de car&aacute;cter personal y del tratamiento que Farmacia los llanos haya realizado o realice, as&iacute; como, entre otra, de la informaci&oacute;n disponible sobre el origen de dichos datos y los destinatarios de las comunicaciones realizadas o previstas de los mismos.</li>
                    <li><em>Derecho de rectificaci&oacute;n</em>: Es el derecho del Usuario a que se modifiquen sus datos personales que resulten ser inexactos o, teniendo en cuenta los fines del tratamiento, incompletos.</li>
                    <li><em>Derecho de supresi&oacute;n ("el derecho al olvido")</em>: Es el derecho del Usuario, siempre que la legislaci&oacute;n vigente no establezca lo contrario, a obtener la supresi&oacute;n de sus datos personales cuando estos ya no sean necesarios para los fines para los cuales fueron recogidos o tratados; el Usuario haya retirado su consentimiento al tratamiento y este no cuente con otra base legal; el Usuario se oponga al tratamiento y no exista otro motivo leg&iacute;timo para continuar con el mismo; los datos personales hayan sido tratados il&iacute;citamente; los datos personales deban suprimirse en cumplimiento de una obligaci&oacute;n legal; o los datos personales hayan sido obtenidos producto de una oferta directa de servicios de la sociedad de la informaci&oacute;n a un menor de 14 a&ntilde;os. Adem&aacute;s de suprimir los datos, el Responsable del tratamiento, teniendo en cuenta la tecnolog&iacute;a disponible y el coste de su aplicaci&oacute;n, deber&aacute; adoptar medidas razonables para informar a los responsables que est&eacute;n tratando los datos personales de la solicitud del interesado de supresi&oacute;n de cualquier enlace a esos datos personales.</li>
                    <li><em>Derecho a la limitaci&oacute;n del tratamiento</em>: Es el derecho del Usuario a limitar el tratamiento de sus datos personales. El Usuario tiene derecho a obtener la limitaci&oacute;n del tratamiento cuando impugne la exactitud de sus datos personales; el tratamiento sea il&iacute;cito; el Responsable del tratamiento ya no necesite los datos personales, pero el Usuario lo necesite para hacer reclamaciones; y cuando el Usuario se haya opuesto al tratamiento.</li>
                    <li><em>Derecho a la portabilidad de los datos</em>: En caso de que el tratamiento se efect&uacute;e por medios automatizados, el Usuario tendr&aacute; derecho a recibir del Responsable del tratamiento sus datos personales en un formato estructurado, de uso com&uacute;n y lectura mec&aacute;nica, y a transmitirlos a otro responsable del tratamiento. Siempre que sea t&eacute;cnicamente posible, el Responsable del tratamiento transmitir&aacute; directamente los datos a ese otro responsable.</li>
                    <li><em>Derecho de oposici&oacute;n</em>: Es el derecho del Usuario a que no se lleve a cabo el tratamiento de sus datos de car&aacute;cter personal o se cese el tratamiento de los mismos por parte de Farmacia los llanos.</li>
                    <li><em>Derecho a no ser</em> <em>a no ser objeto de una decisi&oacute;n basada &uacute;nicamente en el tratamiento</em> <em>automatizado, incluida la elaboraci&oacute;n de perfiles</em>: Es el derecho del Usuario a no ser objeto de una decisi&oacute;n individualizada basada &uacute;nicamente en el tratamiento automatizado de sus datos personales, incluida la elaboraci&oacute;n de perfiles, existente salvo que la legislaci&oacute;n vigente establezca lo contrario.</li>
                </ul>
                <p>As&iacute; pues, el Usuario podr&aacute; ejercitar sus derechos mediante comunicaci&oacute;n escrita dirigida al Responsable del tratamiento con la referencia "RGPD-farmacialosllanos.org", especificando:</p>
                <ul>
                    <li>Nombre, apellidos del Usuario y copia del DNI. En los casos en que se admita la representaci&oacute;n, ser&aacute; tambi&eacute;n necesaria la identificaci&oacute;n por el mismo medio de la persona que representa al Usuario, as&iacute; como el documento acreditativo de la representaci&oacute;n. La fotocopia del DNI podr&aacute; ser sustituida, por cualquier otro medio v&aacute;lido en derecho que acredite la identidad.</li>
                    <li>Petici&oacute;n con los motivos espec&iacute;ficos de la solicitud o informaci&oacute;n a la que se quiere acceder.</li>
                    <li>Domicilio a efecto de notificaciones.</li>
                    <li>Fecha y firma del solicitante.</li>
                    <li>Todo documento que acredite la petici&oacute;n que formula.</li>
                </ul>
                <p>Esta solicitud y todo otro documento adjunto podr&aacute; enviarse a la siguiente direcci&oacute;n y/o correo electr&oacute;nico:</p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Direcci&oacute;n postal: C/ Potasio 7, Loma Cabrera<br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Correo electr&oacute;nico: contacto@farmacialosllanos.org</p>
                <p><strong>Enlaces a sitios web de terceros</strong></p>
                <p>El Sitio Web puede incluir hiperv&iacute;nculos o enlaces que permiten acceder a p&aacute;ginas web de terceros distintos de Farmacia los llanos, y que por tanto no son operados por Farmacia los llanos. Los titulares de dichos sitios web dispondr&aacute;n de sus propias pol&iacute;ticas de protecci&oacute;n de datos, siendo ellos mismos, en cada caso, responsables de sus propios ficheros y de sus propias pr&aacute;cticas de privacidad.</p>
                <p><strong>Reclamaciones ante la autoridad de control</strong></p>
                <p>En caso de que el Usuario considere que existe un problema o infracci&oacute;n de la normativa vigente en la forma en la que se est&aacute;n tratando sus datos personales, tendr&aacute; derecho a la tutela judicial efectiva y a presentar una reclamaci&oacute;n ante una autoridad de control, en particular, en el Estado en el que tenga su residencia habitual, lugar de trabajo o lugar de la supuesta infracci&oacute;n. En el caso de Espa&ntilde;a, la autoridad de control es la Agencia Espa&ntilde;ola de Protecci&oacute;n de Datos (http://www.agpd.es).</p>
                <p><strong>Aceptaci&oacute;n y cambios en esta pol&iacute;tica de privacidad</strong></p>
                <p>Es necesario que el Usuario haya le&iacute;do y est&eacute; conforme con las condiciones sobre la protecci&oacute;n de datos de car&aacute;cter personal contenidas en esta Pol&iacute;tica de Privacidad, as&iacute; como que acepte el tratamiento de sus datos personales para que el Responsable del tratamiento pueda proceder al mismo en la forma, durante los plazos y para las finalidades indicadas. El uso del Sitio Web implicar&aacute; la aceptaci&oacute;n de la Pol&iacute;tica de Privacidad del mismo.</p>
                <p>Farmacia los llanos se reserva el derecho a modificar su Pol&iacute;tica de Privacidad, de acuerdo a su propio criterio, o motivado por un cambio legislativo, jurisprudencial o doctrinal de la Agencia Espa&ntilde;ola de Protecci&oacute;n de Datos. Los cambios o actualizaciones de esta Pol&iacute;tica de Privacidad no ser&aacute;n notificados de forma expl&iacute;cita al Usuario. Se recomienda al Usuario consultar esta p&aacute;gina de forma peri&oacute;dica para estar al tanto de los &uacute;ltimos cambios o actualizaciones.</p>
                <p>Esta Pol&iacute;tica de Privacidad fue actualizada el d&iacute;a 3 de mayo 2021 para adaptarse al Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo, de 27 de abril de 2016, relativo a la protecci&oacute;n de las personas f&iacute;sicas en lo que respecta al tratamiento de datos personales y a la libre circulaci&oacute;n de estos datos (RGPD) y a la Ley Org&aacute;nica 3/2018, de 5 de diciembre, de Protecci&oacute;n de Datos Personales y garant&iacute;a de los derechos digitales (LOPD)</p>

                <p><strong>V. POL&Iacute;TICA DE COOKIES</strong></p>
                <p> El acceso a este Sitio Web puede implicar la utilizaci&oacute;n de cookies. Las cookies son peque&ntilde;as cantidades de informaci&oacute;n que se almacenan en el navegador utilizado por cada Usuario &mdash;en los distintos dispositivos que pueda utilizar para navegar&mdash; para que el servidor recuerde cierta informaci&oacute;n que posteriormente y &uacute;nicamente el servidor que la implement&oacute; leer&aacute;. Las cookies facilitan la navegaci&oacute;n, la hacen m&aacute;s amigable, y no da&ntilde;an el dispositivo de navegaci&oacute;n.</p>
                <p>Las cookies son procedimientos autom&aacute;ticos de recogida de informaci&oacute;n relativa a las preferencias determinadas por el Usuario durante su visita al Sitio Web con el fin de reconocerlo como Usuario, y personalizar su experiencia y el uso del Sitio Web, y pueden tambi&eacute;n, por ejemplo, ayudar a identificar y resolver errores.</p>
                <p>La informaci&oacute;n recabada a trav&eacute;s de las cookies puede incluir la fecha y hora de visitas al Sitio Web, las p&aacute;ginas visionadas, el tiempo que ha estado en el Sitio Web y los sitios visitados justo antes y despu&eacute;s del mismo. Sin embargo, ninguna cookie permite que esta misma pueda contactarse con el n&uacute;mero de tel&eacute;fono del Usuario o con cualquier otro medio de contacto personal. Ninguna cookie puede extraer informaci&oacute;n del disco duro del Usuario o robar informaci&oacute;n personal. La &uacute;nica manera de que la informaci&oacute;n privada del Usuario forme parte del archivo Cookie es que el usuario d&eacute; personalmente esa informaci&oacute;n al servidor.</p>
                <p>Las cookies que permiten identificar a una persona se consideran datos personales. Por tanto, a las mismas les ser&aacute; de aplicaci&oacute;n la Pol&iacute;tica de Privacidad anteriormente descrita. En este sentido, para la utilizaci&oacute;n de las mismas ser&aacute; necesario el consentimiento del Usuario. Este consentimiento ser&aacute; comunicado, en base a una elecci&oacute;n aut&eacute;ntica, ofrecido mediante una decisi&oacute;n afirmativa y positiva, antes del tratamiento inicial, removible y documentado.</p>
                <p><strong>Cookies propias</strong></p>
                <p>Son aquellas cookies que son enviadas al ordenador o dispositivo del Usuario y gestionadas exclusivamente por Farmacia los llanos para el mejor funcionamiento del Sitio Web. La informaci&oacute;n que se recaba se emplea para mejorar la calidad del Sitio Web y su Contenido y su experiencia como Usuario. Estas cookies permiten reconocer al Usuario como visitante recurrente del Sitio Web y adaptar el contenido para ofrecerle contenidos que se ajusten a sus preferencias.</p>
                <p><strong>Cookies de terceros</strong></p>
                <p>Son cookies utilizadas y gestionadas por entidades externas que proporcionan a Farmacia los llanos servicios solicitados por este mismo para mejorar el Sitio Web y la experiencia del usuario al navegar en el Sitio Web. Los principales objetivos para los que se utilizan cookies de terceros son la obtenci&oacute;n de estad&iacute;sticas de accesos y analizar la informaci&oacute;n de la navegaci&oacute;n, es decir, c&oacute;mo interact&uacute;a el Usuario con el Sitio Web.</p>
                <p>La informaci&oacute;n que se obtiene se refiere, por ejemplo, al n&uacute;mero de p&aacute;ginas visitadas, el idioma, el lugar a la que la direcci&oacute;n IP desde el que accede el Usuario, el n&uacute;mero de Usuarios que acceden, la frecuencia y reincidencia de las visitas, el tiempo de visita, el navegador que usan, el operador o tipo de dispositivo desde el que se realiza la visita. Esta informaci&oacute;n se utiliza para mejorar el Sitio Web, y detectar nuevas necesidades para ofrecer a los Usuarios un Contenido y/o servicio de &oacute;ptima calidad. En todo caso, la informaci&oacute;n se recopila de forma an&oacute;nima y se elaboran informes de tendencias del Sitio Web sin identificar a usuarios individuales.</p>
                <p>Puede obtener m&aacute;s informaci&oacute;n sobre las cookies, la informaci&oacute;n sobre la privacidad, o consultar la descripci&oacute;n del tipo de cookies que se utiliza, sus principales caracter&iacute;sticas, periodo de expiraci&oacute;n, etc. en el siguiente(s) enlace(s):</p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Google Analytics: <a href="https://developers.google.com/analytics/">https://developers.google.com/analytics/</a></p>
                <p>La(s) entidad(es) encargada(s) del suministro de cookies podr&aacute;(n) ceder esta informaci&oacute;n a terceros, siempre y cuando lo exija la ley o sea un tercero el que procese esta informaci&oacute;n para dichas entidades.</p>
                <p><strong>Cookies de redes sociales</strong></p>
                <p>Farmacia los llanos incorpora plugins de redes sociales, que permiten acceder a las mismas a partir del Sitio Web. Por esta raz&oacute;n, las cookies de redes sociales pueden almacenarse en el navegador del Usuario. Los titulares de dichas redes sociales disponen de sus propias pol&iacute;ticas de protecci&oacute;n de datos y de cookies, siendo ellos mismos, en cada caso, responsables de sus propios ficheros y de sus propias pr&aacute;cticas de privacidad. El Usuario debe referirse a las mismas para informarse acerca de dichas cookies y, en su caso, del tratamiento de sus datos personales. &Uacute;nicamente a t&iacute;tulo informativo se indican a continuaci&oacute;n los enlaces en los que se pueden consultar dichas pol&iacute;ticas de privacidad y/o de cookies:</p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Facebook: <a href="https://www.facebook.com/policies/cookies/">https://www.facebook.com/policies/cookies/</a></p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Twitter: <a href="https://twitter.com/es/privacy">https://twitter.com/es/privacy</a></p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Instagram: <a href="https://help.instagram.com/1896641480634370?ref=ig">https://help.instagram.com/1896641480634370?ref=ig</a></p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Youtube: <a href="https://policies.google.com/privacy?hl=es-419&gl=mx">https://policies.google.com/privacy?hl=es-419&amp;gl=mx</a></p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Google+: <a href="https://policies.google.com/technologies/cookies?hl=es">https://policies.google.com/technologies/cookies?hl=es</a></p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Pinterest: <a href="https://policy.pinterest.com/es/privacy-policy">https://policy.pinterest.com/es/privacy-policy</a></p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;LinkedIn: <a href="https://www.linkedin.com/legal/cookie-policy?trk=hp-cookies">https://www.linkedin.com/legal/cookie-policy?trk=hp-cookies</a></p>
                <p><strong>Deshabilitar, rechazar y eliminar cookies</strong></p>
                <p>El Usuario puede deshabilitar, rechazar y eliminar las cookies &mdash;total o parcialmente&mdash; instaladas en su dispositivo mediante la configuraci&oacute;n de su navegador (entre los que se encuentran, por ejemplo, Chrome, Firefox, Safari, Explorer). En este sentido, los procedimientos para rechazar y eliminar las cookies pueden diferir de un navegador de Internet a otro. En consecuencia, el Usuario debe acudir a las instrucciones facilitadas por el propio navegador de Internet que est&eacute; utilizando. En el supuesto de que rechace el uso de cookies &mdash;total o parcialmente&mdash; podr&aacute; seguir usando el Sitio Web, si bien podr&aacute; tener limitada la utilizaci&oacute;n de algunas de las prestaciones del mismo.</p>
                <p><strong>Cambios en la Pol&iacute;tica de Cookies</strong></p>
                <p>Es posible que la Pol&iacute;tica de Cookies del Sitio Web cambie o se actualice, por ello es recomendable que el Usuario revise esta pol&iacute;tica cada vez que acceda al Sitio Web con el objetivo de estar adecuadamente informado sobre c&oacute;mo y para qu&eacute; usamos las cookies.</p>

                <p><strong>VI. POL&Iacute;TICA DE ENLACES</strong></p>
                <p> Se informa que el Sitio Web de Farmacia los llanos pone o puede poner a disposici&oacute;n de los Usuarios medios de enlace (como, entre otros, links, banners, botones), directorios y motores de b&uacute;squeda que permiten a los Usuarios acceder a sitios web pertenecientes y/o gestionados por terceros.</p>
                <p>La instalaci&oacute;n de estos enlaces, directorios y motores de b&uacute;squeda en el Sitio Web tiene por objeto facilitar a los Usuarios la b&uacute;squeda de y acceso a la informaci&oacute;n disponible en Internet, sin que pueda considerarse una sugerencia, recomendaci&oacute;n o invitaci&oacute;n para la visita de los mismos.</p>
                <p>Farmacia los llanos no ofrece ni comercializa por s&iacute; ni por medio de terceros los productos y/o servicios disponibles en dichos sitios enlazados.</p>
                <p>Asimismo, tampoco garantizar&aacute; la disponibilidad t&eacute;cnica, exactitud, veracidad, validez o legalidad de sitios ajenos a su propiedad a los que se pueda acceder por medio de los enlaces.</p>
                <p>Farmacia los llanos en ning&uacute;n caso revisar&aacute; o controlar&aacute; el contenido de otros sitios web, as&iacute; como tampoco aprueba, examina ni hace propios los productos y servicios, contenidos, archivos y cualquier otro material existente en los referidos sitios enlazados.</p>
                <p>Farmacia los llanos no asume ninguna responsabilidad por los da&ntilde;os y perjuicios que pudieran producirse por el acceso, uso, calidad o licitud de los contenidos, comunicaciones, opiniones, productos y servicios de los sitios web no gestionados por Farmacia los llanos y que sean enlazados en este Sitio Web.</p>
                <p>El Usuario o tercero que realice un hiperv&iacute;nculo desde una p&aacute;gina web de otro, distinto, sitio web al Sitio Web de Farmacia los llanos deber&aacute; saber que:</p>
                <p>No se permite la reproducci&oacute;n &mdash;total o parcialmente&mdash; de ninguno de los Contenidos y/o Servicios del Sitio Web sin autorizaci&oacute;n expresa de Farmacia los llanos.</p>
                <p>No se permite tampoco ninguna manifestaci&oacute;n falsa, inexacta o incorrecta sobre el Sitio Web de Farmacia los llanos, ni sobre los Contenidos y/o Servicios del mismo.</p>
                <p>A excepci&oacute;n del hiperv&iacute;nculo, el sitio web en el que se establezca dicho hiperenlace no contendr&aacute; ning&uacute;n elemento, de este Sitio Web, protegido como propiedad intelectual por el ordenamiento jur&iacute;dico espa&ntilde;ol, salvo autorizaci&oacute;n expresa de Farmacia los llanos.</p>
                <p>El establecimiento del hiperv&iacute;nculo no implicar&aacute; la existencia de relaciones entre Farmacia los llanos y el titular del sitio web desde el cual se realice, ni el conocimiento y aceptaci&oacute;n de Farmacia los llanos de los contenidos, servicios y/o actividades ofrecidos en dicho sitio web, y viceversa.</p>

                <p><strong> VII. PROPIEDAD INTELECTUAL E INDUSTRIAL</strong></p>
                <p> Farmacia los llanos por s&iacute; o como parte cesionaria, es titular de todos los derechos de propiedad intelectual e industrial del Sitio Web, as&iacute; como de los elementos contenidos en el mismo (a t&iacute;tulo enunciativo y no exhaustivo, im&aacute;genes, sonido, audio, v&iacute;deo, software o textos, marcas o logotipos, combinaciones de colores, estructura y dise&ntilde;o, selecci&oacute;n de materiales usados, programas de ordenador necesarios para su funcionamiento, acceso y uso, etc.). Ser&aacute;n, por consiguiente, obras protegidas como propiedad intelectual por el ordenamiento jur&iacute;dico espa&ntilde;ol, si&eacute;ndoles aplicables tanto la normativa espa&ntilde;ola y comunitaria en este campo, como los tratados internacionales relativos a la materia y suscritos por Espa&ntilde;a.</p>
                <p>Todos los derechos reservados. En virtud de lo dispuesto en la Ley de Propiedad Intelectual, quedan expresamente prohibidas la reproducci&oacute;n, la distribuci&oacute;n y la comunicaci&oacute;n p&uacute;blica, incluida su modalidad de puesta a disposici&oacute;n, de la totalidad o parte de los contenidos de esta p&aacute;gina web, con fines comerciales, en cualquier soporte y por cualquier medio t&eacute;cnico, sin la autorizaci&oacute;n de Farmacia los llanos.</p>
                <p>El Usuario se compromete a respetar los derechos de propiedad intelectual e industrial de Farmacia los llanos. Podr&aacute; visualizar los elementos del Sitio Web o incluso imprimirlos, copiarlos y almacenarlos en el disco duro de su ordenador o en cualquier otro soporte f&iacute;sico siempre y cuando sea, exclusivamente, para su uso personal. El Usuario, sin embargo, no podr&aacute; suprimir, alterar, o manipular cualquier dispositivo de protecci&oacute;n o sistema de seguridad que estuviera instalado en el Sitio Web.</p>
                <p>En caso de que el Usuario o tercero considere que cualquiera de los Contenidos del Sitio Web suponga una violaci&oacute;n de los derechos de protecci&oacute;n de la propiedad intelectual, deber&aacute; comunicarlo inmediatamente a Farmacia los llanos a trav&eacute;s de los datos de contacto del apartado de INFORMACI&Oacute;N GENERAL de este Aviso Legal y Condiciones Generales de Uso.</p>

                <p><strong> VIII. ACCIONES LEGALES, LEGISLACI&Oacute;N APLICABLE Y JURISDICCI&Oacute;N</strong></p>
                <p>Farmacia los llanos se reserva la facultad de presentar las acciones civiles o penales que considere necesarias por la utilizaci&oacute;n indebida del Sitio Web y Contenidos, o por el incumplimiento de las presentes Condiciones.</p>
                <p>La relaci&oacute;n entre el Usuario y Farmacia los llanos se regir&aacute; por la normativa vigente y de aplicaci&oacute;n en el territorio espa&ntilde;ol. De surgir cualquier controversia en relaci&oacute;n a la interpretaci&oacute;n y/o a la aplicaci&oacute;n de estas Condiciones las partes someter&aacute;n sus conflictos a la jurisdicci&oacute;n ordinaria someti&eacute;ndose a los jueces y tribunales que correspondan conforme a derecho.</p>
                
                <p><strong> IX. HERBOLARIOS, PARAFARMACIAS</strong></p>
                <p>Este comerciante se compromete a no permitir ninguna transacción que sea ilegal, o se considere por las marcas de tarjetas de crédito o el banco adquiriente, que pueda o tenga el potencial de dañar la buena voluntad de los mismos o influir de manera negativa en ellos. Las siguientes actividades están prohibidas en virtud de los programas de las marcas de tarjetas: la venta u oferta de un producto o servicio que no sea de plena conformidad con todas las leyes aplicables al Comprador, Banco Emisor, Comerciante, Titular de la tarjeta, o tarjetas. Además, las siguientes actividades también están prohibidas explícitamente:</p>
                <ul>
                    <li>Vender medicamentos</li>
                </ul>
                
                <p>Ultima modificaci&oacute;n: 10 de abril 2023</p>
                
                
            </div>
        </div>
    </div>

    <?php sectioncookies($trans);?>
    <?php sectionfooter($trans);?>

    <?php sectionjs();?>
</body>